modified TDengine to DThouse

diff --git a/src/kit/taos-tools/.github/workflows/cmake-release.yml b/src/kit/taos-tools/.github/workflows/cmake-release.yml
--- a/src/kit/taos-tools/.github/workflows/cmake-release.yml
+++ b/src/kit/taos-tools/.github/workflows/cmake-release.yml
@@ -28,8 +28,8 @@ jobs:
         uses: actions/checkout@v2
         with:
           submodules: recursive
-          repository: 'taosdata/TDengine'
-          path: 'TDengine'
+          repository: 'taosdata/DThouse'
+          path: 'DThouse'
           ref: 'develop'
 
       - name: Change time zone
@@ -37,18 +37,18 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #- name: Checkout TDengine with same branch of taos-tools
+          #- name: Checkout DThouse with same branch of taos-tools
           #run: |
-          #cd TDengine
+          #cd DThouse
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
+          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in DThouse"
           #git submodule update --init --recursive
           #if: github.event_name == 'pull_request'
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Checkout DThouse's taos-tools to PR number
         if: github.event_name == 'pull_request'
         run: |
-          cd TDengine/src/kit/taos-tools
+          cd DThouse/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
           git submodule update --init --recursive
@@ -61,11 +61,11 @@ jobs:
       - name: Install tdengine
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
-          cd TDengine && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DBUILD_TYPE=Release -DBUILD_HTTP=false && make && sudo make install
+          cd DThouse && mkdir release && cd release && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true -DBUILD_TYPE=Release -DBUILD_HTTP=false && make && sudo make install
 
       - name: Func Test
         run: |
-          cd TDengine/tests/pytest
+          cd DThouse/tests/pytest
           pip3 install taospy numpy fabric2 psutil pandas faker
           sudo pkill -9 taosadapter || :
           sudo pkill -9 taosd || :
@@ -77,7 +77,7 @@ jobs:
 
       - name: System Test
         run: |
-          cd TDengine/tests/system-test
+          cd DThouse/tests/system-test
           if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
           then
             for i in `find 5-taos-tools/taosdump -name "*.py"`; do python3 ./test.py -f $i > /dev/null 2>&1 && echo -e "\033[32m $i success! \033[0m"|| echo -e "\033[31m $i failed! \033[0m" | tee -a taosdump-failed.txt; done
@@ -93,7 +93,7 @@ jobs:
 
       - name: Develop Test
         run: |
-          cd TDengine/tests/develop-test
+          cd DThouse/tests/develop-test
 
           if find 5-taos-tools/taosdump -name "*.py"|grep -q .;
           then
diff --git a/src/kit/taos-tools/.github/workflows/codecov.yml b/src/kit/taos-tools/.github/workflows/codecov.yml
--- a/src/kit/taos-tools/.github/workflows/codecov.yml
+++ b/src/kit/taos-tools/.github/workflows/codecov.yml
@@ -34,8 +34,8 @@ jobs:
         uses: actions/checkout@v2
         with:
           submodules: recursive
-          repository: 'taosdata/TDengine'
-          path: 'TDengine'
+          repository: 'taosdata/DThouse'
+          path: 'DThouse'
           ref: 'develop'
 
       - name: Change time zone
@@ -43,28 +43,28 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #      - name: Checkout TDengine with same branch of taos-tools
+          #      - name: Checkout DThouse with same branch of taos-tools
           #run: |
-          #cd TDengine
+          #cd DThouse
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
+          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in DThouse"
           #git submodule update --init --recursive
           #if: github.event_name == 'pull_request'
 
       - name: Install packages
         run: sudo apt-get install lzma-dev libjansson-dev libsnappy-dev -y > /dev/null
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Checkout DThouse's taos-tools to PR number
         if: github.event_name == 'pull_request'
         run: |
-          cd TDengine/src/kit/taos-tools
+          cd DThouse/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
 
       - name: Install tdengine
         run: |
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y > /dev/null
-          cd TDengine
+          cd DThouse
           mkdir debug
           cd debug
           cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=true -DBUILD_TOOLS=true -DCOVER=true -DBUILD_TYPE=Debug
@@ -133,7 +133,7 @@ jobs:
 
       - name: Generate report
         run: |
-          cd TDengine/debug
+          cd DThouse/debug
           gcov -abcfu ../src/kit/taos-tools/src/taosdump.c -o src/kit/taos-tools/src/CMakeFiles/taosdump.dir/taosdump.c.gcno
           gcov -abcfu ../src/kit/taos-tools/src/benchMain.c -o src/kit/taos-tools/src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
           gcov -abcfu ../src/kit/taos-tools/src/benchCommandOpt.c -o src/kit/taos-tools/src/CMakeFiles/taosbench.dir/benchCommandOpt.c.gcno
@@ -149,4 +149,4 @@ jobs:
         uses: codecov/codecov-action@v2.1.0
         with:
          token: ${{ secrets.CODECOV_TOKEN }}
-         files: TDengine/debug/taosdump.c.gcov,TDengine/debug/benchMain.c.gcov,TDengine/debug/benchCommandOpt.c.gcov,TDengine/debug/benchData.c.gcov,TDengine/debug/benchInsert.c.gcov,TDengine/debug/benchJsonOpt.c.gcov,TDengine/debug/benchOutput.c.gcov,TDengine/debug/benchQuery.c.gcov,TDengine/debug/benchSubscribe.c.gcov,TDengine/debug/benchUtil.c.gcov
+         files: DThouse/debug/taosdump.c.gcov,DThouse/debug/benchMain.c.gcov,DThouse/debug/benchCommandOpt.c.gcov,DThouse/debug/benchData.c.gcov,DThouse/debug/benchInsert.c.gcov,DThouse/debug/benchJsonOpt.c.gcov,DThouse/debug/benchOutput.c.gcov,DThouse/debug/benchQuery.c.gcov,DThouse/debug/benchSubscribe.c.gcov,DThouse/debug/benchUtil.c.gcov
diff --git a/src/kit/taos-tools/.github/workflows/coveralls.yml b/src/kit/taos-tools/.github/workflows/coveralls.yml
--- a/src/kit/taos-tools/.github/workflows/coveralls.yml
+++ b/src/kit/taos-tools/.github/workflows/coveralls.yml
@@ -34,8 +34,8 @@ jobs:
         uses: actions/checkout@v2
         with:
           submodules: recursive
-          repository: 'taosdata/TDengine'
-          path: 'TDengine'
+          repository: 'taosdata/DThouse'
+          path: 'DThouse'
           ref: 'develop'
 
       - name: Change time zone
@@ -43,30 +43,30 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #      - name: Checkout TDengine with same branch of taos-tools
+          #      - name: Checkout DThouse with same branch of taos-tools
           #run: |
-          #cd TDengine
+          #cd DThouse
           #git pull
           #git branch -a | grep -w ${{ github.head_ref }} \
           #  && git checkout ${{ github.head_ref }} \
           #  && git submodule update --init --recursive \
-          #  || echo "${{ github.head_ref }} not found in TDengine"
+          #  || echo "${{ github.head_ref }} not found in DThouse"
 
           #if: github.event_name == 'pull_request'
 
       - name: Install packages
         run: sudo apt-get install lzma-dev liblzma-dev libjansson-dev libz-dev libsnappy-dev pkg-config lcov -y > /dev/null
 
-      - name: Checkout TDengine's taos-tools to develop latest
+      - name: Checkout DThouse's taos-tools to develop latest
         run: |
-          cd TDengine/src/kit/taos-tools
+          cd DThouse/src/kit/taos-tools
           git checkout develop
           git pull
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Checkout DThouse's taos-tools to PR number
         if: github.event_name == 'pull_request'
         run: |
-          cd TDengine/src/kit/taos-tools
+          cd DThouse/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
           git submodule update --init --recursive
@@ -78,7 +78,7 @@ jobs:
 
       - name: Install tdengine
         run: |
-          cd TDengine
+          cd DThouse
           mkdir debug
           cd debug
           cmake .. -DBUILD_JDBC=false -DBUILD_HTTP=false -DBUILD_TOOLS=true -DCOVER=true -DBUILD_TYPE=Debug > /dev/null 2>&1
@@ -200,17 +200,17 @@ jobs:
       - name: Generate report
         run: |
           topdir=`pwd`
-          cd TDengine/debug/src/kit/taos-tools
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
-          gcov -abcfu ${topdir}/TDengine/src/kit/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
+          cd DThouse/debug/src/kit/taos-tools
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/taosdump.c -o src/CMakeFiles/taosdump.dir/taosdump.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchMain.c -o src/CMakeFiles/taosBenchmark.dir/benchMain.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchCommandOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchCommandOpt.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchData.c -o src/CMakeFiles/taosBenchmark.dir/benchData.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchInsert.c -o src/CMakeFiles/taosBenchmark.dir/benchInsert.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchJsonOpt.c -o src/CMakeFiles/taosBenchmark.dir/benchJsonOpt.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchOutput.c -o src/CMakeFiles/taosBenchmark.dir/benchOutput.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchQuery.c -o src/CMakeFiles/taosBenchmark.dir/benchQuery.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchSubscribe.c -o src/CMakeFiles/taosBenchmark.dir/benchSubscribe.c.gcno
+          gcov -abcfu ${topdir}/DThouse/src/kit/taos-tools/src/benchUtil.c -o src/CMakeFiles/taosBenchmark.dir/benchUtil.c.gcno
           mkdir ${topdir}/coverage || :
           lcov -c -d . -o ${topdir}/coverage/lcov-with-deps.info
           lcov -r ${topdir}/coverage/lcov-with-deps.info "*/deps/*" -o ${topdir}/coverage/lcov.info
diff --git a/src/kit/taos-tools/.github/workflows/non-x64.yml b/src/kit/taos-tools/.github/workflows/non-x64.yml
--- a/src/kit/taos-tools/.github/workflows/non-x64.yml
+++ b/src/kit/taos-tools/.github/workflows/non-x64.yml
@@ -61,8 +61,8 @@ jobs:
         uses: actions/checkout@v2
         with:
           submodules: recursive
-          repository: 'taosdata/TDengine'
-          path: 'TDengine'
+          repository: 'taosdata/DThouse'
+          path: 'DThouse'
           ref: 'develop'
 
       - name: Change time zone
@@ -71,20 +71,20 @@ jobs:
           sudo timedatectl set-timezone Asia/Shanghai
           sudo date
 
-          #- name: Checkout TDengine with same branch of taos-tools
+          #- name: Checkout DThouse with same branch of taos-tools
           #run: |
           #echo "The uname output was ${{ steps.setup.outputs.uname }}"
-          #cd TDengine
+          #cd DThouse
           #git pull
-          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in TDengine"
+          #git branch -a | grep -w ${{ github.head_ref }} && git checkout ${{ github.head_ref }} || echo "${{ github.head_ref }} not found in DThouse"
           #git submodule update --init --recursive
           #if: github.event_name == 'pull_request'
 
-      - name: Checkout TDengine's taos-tools to PR number
+      - name: Checkout DThouse's taos-tools to PR number
         if: github.event_name == 'pull_request'
         run: |
           echo "The uname output was ${{ steps.setup.outputs.uname }}"
-          cd TDengine/src/kit/taos-tools
+          cd DThouse/src/kit/taos-tools
           git fetch origin +refs/pull/${{env.PR_NUMBER}}/merge
           git checkout -qf FETCH_HEAD
           git submodule update --init --recursive
@@ -93,7 +93,7 @@ jobs:
         run: |
           echo "The uname output was ${{ steps.setup.outputs.uname }}"
           sudo apt install libjansson-dev libsnappy-dev liblzma-dev libz-dev pkg-config -y
-          cd TDengine
+          cd DThouse
           mkdir debug
           cd debug
           cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=true
